apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "deploy.yaml"
    branches:
    - ^main$
    - ^master$    
    queries:
    - excludedBranches: {}
      included_branches: {}
      labels:
        entries:
        - deploy
      milestone: ""
      missingLabels:
        entries:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
      review_approved_required: false
    - excludedBranches: {}
      included_branches: {}
      labels:
        entries:
        - env/staging
        - updatebot
      milestone: ""
      missingLabels:
        entries:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
      review_approved_required: false
